spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 246e57fc332ed4bf7b4c7fcbb9491499
            client-secret: NmWytHrvBBD42aKfAqsjAUOPlTo0WUMM
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: account_email
            client-authentication-method: client_secret_post
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: POST
            user-name-attribute: id

  datasource:
    url: jdbc:mysql://localhost:3306/withme
    username: withme
    password: tjr72902!!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

study-with-me:
  token:
    secret-key: studywithme2312321w23213r323213213eqwwxlqwweqw
    expiration: 1800000       # 30 minute
    refresh-token:
      expiration: 604800000   # 7 days