spring:
  datasource:
    url: jdbc:mysql://localhost:3306/withme
    username: withme
    password: tjr72902!!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
